package types

const Golang = "go"
const NodeLatestLang = "node_latest"
const PerlLtsLang = "perl"
const NodeEsmLtsLang = "node_latest_esm"
const Python2Lang = "python2"
const Python3Lang = "python3"
const LuaLang = "lua"
const RubyLang = "ruby"
const PHP74Lang = "php74"
const RustLang = "rust"
const HaskellLang = "haskell"
const C = "c"
const CPlusPlusLang = "c++"
const CSharpLang = "c_sharp_mono"
const JuliaLang = "julia"
const JavaLang = "java"
const KotlinLang = "kotlin"
const ZigLang = "zig"
const BashLang = "bash"
const DartLang = "dart"

//const SwiftLang = "swift"
